export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SERVICE_ADVISOR = 'SERVICE_ADVISOR',
  MECHANIC = 'MECHANIC',
  STOCK_KEEPER = 'STOCK_KEEPER',
  FINANCIAL = 'FINANCIAL',
  CASHIER = 'CASHIER',
  CUSTOMER = 'CUSTOMER',
}
